version: 1
option1: option1-value
option2: option2-value
falsyBooleanOption: false
falsyNumericOption: 0
falsyStringOption: ''
bracketedOption: '[value]'
ignoredOption: '/* placeholder */'
parentOption:
  nestedOption: 'nestedOption-value'
